### ISSUE TITLE
Redragon Draconic

### ISSUE THREAD

**Issue by souovan** [dokutan/rgb_keyboard#23]
I don't know if this is the right place to make this question, but here it goes: There is any plan to add support to Redragon Draconic keyboard ?

ps.: if there isn't the place please close this issue.

**Comment by dokutan** [comment]
I have generally no plans to add support for more keyboards on my own, because supporting a new keyboard requires physical access to it. This means, if you want support for the Redragon Draconic, you would have to provide:
- at least the USB vendor and product ids
- feedback/testing after features are implemented
- potentially captures of the communication with the official software

I further suggest you look at the closed issues regarding support for new keyboards if you are interested.

**Comment by souovan** [comment]
Thank you for you feedback!
